### PR TITLE
DG-16073: Set valid subtype in content type header

### PR DESCRIPTION
**Pull request by erindethorne**
We're setting the content type header on responses to `Content-type: image`. To my knowledge, the format of the content type values is expected to be type/subtype (for example `image/png`).

This can manifest as an issue when requesting the processed image as a blob in an xhr request. In Chrome everything is fine, but in Firefox since the content type is not fully formed, it assumes application/xml and responding javascript misinterprets the image. See this fiddle in Chrome versus Firefox for more detail: https://jsfiddle.net/uvkv7vq1/3/

### CODE REVIEW

**Comment by ayobami14** [comment]
LGTM, @richardadjogah should probably take a look.
Also, did you check with Walking Devs/Webs to see if there's anyway this may affect them. I remember that being a concern in grooming

**Comment by richardadjogah** [comment]
This looks fine to me as long as we can ensure that all possible values of `imageExtension` are valid content type headers when appended to 'image'. I'm confident that png and jpeg are fine, but there's a few other file types that the app supports that this should ideally handle (notably BMP and TIF iirc, but the full list should be found somewhere in the codebase)

**Comment by erindethorne** [comment]
I looked up the content type headers for bmp and tiff - they're `image/bmp` and `image/tiff` which align with file extensions.

Can you help me find where in the codebase there is a list of supported file types? If so I can add it to the documentation too.

**Comment by erindethorne** [comment]
Looks like the only 4 extension types supported are `png`, `jpeg`, `webp`, and `gif` - everything else gets converted to jpg. This is based on https://github.com/websdotcom/node-url-imaging/blob/master/src/imageHelper.js#L24. All 4 of these extensions map to valid mime types in a content type header.

**Pull request merged**
